version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development
    env_file:
      - ./client/.env
    networks:
      - tiktok-network

networks:
  tiktok-network:
    driver: bridge
